/*
 * maelys-hello: reference product CLI built on libmaelys_cli. It doubles as
 * the end-to-end fixture of tests/test_cli.sh and shows one command of each
 * effect and output mode.
 */
#include <maelys/cli.h>

#include "hello_schemas.h" /* generated by maelys-cli-embed from schemas/ */

#include <errno.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#define HELLO_VERSION "0.1.0"

/* ---- greet ---------------------------------------------------------------- */

static const maelys_cli_operand_t greet_operands[] = {
    {MAELYS_CLI_OPERAND("NAME", "Person or system to greet.")},
};
static const maelys_cli_option_t greet_options[] = {
    {MAELYS_CLI_FLAG("shout", "Render the greeting in capitals.")},
    {MAELYS_CLI_UNSIGNED("times", "N", "Repeat the greeting.", 1u, 10u),
     .default_text = "1"},
    /* Hidden: accepted and listed by describe, absent from usage, help and
     * completion. */
    {MAELYS_CLI_FLAG("trace", "Report the parsed input on stderr; diagnostics."),
     .hidden = 1},
};

static int command_greet(maelys_cli_context_t *context) {
    const char *name = maelys_cli_operand(context, 0u);
    uint64_t times = 1u;
    (void)maelys_cli_option_unsigned(context, "times", &times);
    if (maelys_cli_flag(context, "trace"))
        maelys_cli_warn(context, "greet: name=%s times=%llu shout=%d", name,
            (unsigned long long)times, maelys_cli_flag(context, "shout"));
    /* --verbose details and --progress are trunk diagnostics: stderr, text
     * mode only, silent in JSON. */
    maelys_cli_detail(context, "greeting %s %llu time(s)", name,
        (unsigned long long)times);
    maelys_cli_progress(context, "greeting %s", name);
    maelys_cli_progress_done(context);
    char greeting[256];
    (void)snprintf(greeting, sizeof(greeting), "Hello, %s!", name);
    if (maelys_cli_flag(context, "shout"))
        for (char *p = greeting; *p; ++p)
            if (*p >= 'a' && *p <= 'z') *p = (char)(*p - 'a' + 'A');
    char human[4096];
    size_t used = 0u;
    for (uint64_t i = 0u; i < times; ++i) {
        int written = snprintf(human + used, sizeof(human) - used, "%s\n", greeting);
        if (written < 0 || (size_t)written >= sizeof(human) - used) break;
        used += (size_t)written;
    }
    maelys_cli_json_writer_t data;
    maelys_cli_json_writer_init(&data);
    (void)maelys_cli_json_begin_object(&data);
    (void)maelys_cli_json_key_string(&data, "greeting", greeting);
    (void)maelys_cli_json_key_unsigned(&data, "times", times);
    (void)maelys_cli_json_end_object(&data);
    return maelys_cli_succeed_writer(context, &data, human, MAELYS_CLI_EXIT_OK);
}

/* ---- limits (typed values) ------------------------------------------------ */

static const char *const level_choices[] = {"low", "high", NULL};
static const maelys_cli_option_t limits_options[] = {
    {MAELYS_CLI_SIZE("memory", "BYTES", "Memory ceiling; K/M/G accepted.", 1u, 0u),
     .default_text = "1G"},
    {MAELYS_CLI_DURATION("wall-time", "DURATION",
     "Deadline with a unit such as 30s or 5m.", 0u, 0u), .default_text = "10m"},
    {MAELYS_CLI_CHOICE("level", "Verbosity level.", level_choices),
     .default_text = "low"},
    {MAELYS_CLI_INTEGER("offset", "N", "Signed adjustment.", -100, 100),
     .default_text = "0"},
    {MAELYS_CLI_HEX("digest", "HEX", "Expected SHA-256 digest.", 64u)},
    {MAELYS_CLI_STRING("tag", "TEXT", "Free label; repeatable."), .repeatable = 1},
    {MAELYS_CLI_FLAG("strict", "Refuse defaults."), .depends_on = "level"},
    {MAELYS_CLI_FLAG("lenient", "Accept defaults."), .conflicts_with = "strict"},
};

static int command_limits(maelys_cli_context_t *context) {
    uint64_t memory = UINT64_C(1) << 30;
    uint64_t wall_time = 600000u;
    int64_t offset = 0;
    size_t level = 0u;
    (void)maelys_cli_option_unsigned(context, "memory", &memory);
    (void)maelys_cli_option_unsigned(context, "wall-time", &wall_time);
    (void)maelys_cli_option_integer(context, "offset", &offset);
    (void)maelys_cli_option_choice(context, "level", &level);
    maelys_cli_json_writer_t data;
    maelys_cli_json_writer_init(&data);
    (void)maelys_cli_json_begin_object(&data);
    (void)maelys_cli_json_key_unsigned(&data, "memory", memory);
    (void)maelys_cli_json_key_unsigned(&data, "wallTimeMs", wall_time);
    (void)maelys_cli_json_key_string(&data, "level", level_choices[level]);
    (void)maelys_cli_json_key_integer(&data, "offset", offset);
    if (maelys_cli_option(context, "digest"))
        (void)maelys_cli_json_key_string(&data, "digest",
            maelys_cli_option(context, "digest"));
    (void)maelys_cli_json_key(&data, "tags");
    (void)maelys_cli_json_begin_array(&data);
    size_t tags = maelys_cli_option_count(context, "tag");
    for (size_t i = 0u; i < tags; ++i)
        (void)maelys_cli_json_string(&data, maelys_cli_option_at(context, "tag", i));
    (void)maelys_cli_json_end_array(&data);
    (void)maelys_cli_json_end_object(&data);
    char human[256];
    (void)snprintf(human, sizeof(human),
        "memory=%" PRIu64 " wallTimeMs=%" PRIu64 " level=%s offset=%" PRId64
        " tags=%zu", memory, wall_time, level_choices[level], offset, tags);
    return maelys_cli_succeed_writer(context, &data, human, MAELYS_CLI_EXIT_OK);
}

/* ---- note write (plan/apply transaction) ---------------------------------- */

static const maelys_cli_operand_t note_operands[] = {
    {MAELYS_CLI_OPERAND("FILE", "Destination file; never overwritten without --replace.")},
};
static const maelys_cli_option_t note_options[] = {
    {MAELYS_CLI_STRING("content", "TEXT", "Text to store."), .required = 1},
    {MAELYS_CLI_FLAG("replace", "Allow replacing an existing file atomically.")},
    MAELYS_CLI_APPLY_OPTION,
};

static int command_note_write(maelys_cli_context_t *context) {
    const char *path = maelys_cli_operand(context, 0u);
    const char *content = maelys_cli_option(context, "content");
    int replace = maelys_cli_flag(context, "replace");
    int apply = maelys_cli_flag(context, "apply");
    struct stat status;
    int absent = lstat(path, &status) != 0 && errno == ENOENT;
    if (!absent && !replace) {
        return maelys_cli_fail(context, MAELYS_CLI_CODE_PRECONDITION_FAILED,
            "Choose a new path or add --replace to overwrite atomically.",
            "Target %s already exists.", path);
    }
    if (apply && maelys_cli_write_file_atomic(path, content, strlen(content),
            0644, replace ? MAELYS_CLI_WRITE_REPLACE :
            MAELYS_CLI_WRITE_NO_REPLACE) != 0) {
        return maelys_cli_fail_errno(context, MAELYS_CLI_CODE_IO_FAILED, errno,
            path);
    }
    maelys_cli_json_writer_t data;
    maelys_cli_json_writer_init(&data);
    (void)maelys_cli_json_begin_object(&data);
    (void)maelys_cli_json_key_string(&data, "mode", apply ? "apply" : "plan");
    (void)maelys_cli_json_key_boolean(&data, "changed", apply);
    (void)maelys_cli_json_key_string(&data, "path", path);
    (void)maelys_cli_json_key_unsigned(&data, "bytes", (uint64_t)strlen(content));
    (void)maelys_cli_json_key(&data, "precondition");
    (void)maelys_cli_json_begin_object(&data);
    (void)maelys_cli_json_key_boolean(&data, "targetAbsent", absent);
    (void)maelys_cli_json_key_boolean(&data, "replace", replace);
    (void)maelys_cli_json_end_object(&data);
    (void)maelys_cli_json_end_object(&data);
    return maelys_cli_succeed_writer(context, &data, apply ?
        "Note written." : "Plan only; add --apply to write the note.",
        MAELYS_CLI_EXIT_OK);
}

/* ---- list (records) --------------------------------------------------------- */

static const maelys_cli_option_t list_options[] = {
    {MAELYS_CLI_UNSIGNED("limit", "N", "Maximum number of records.", 0u, 1000u),
     .default_text = "5"},
};

static int command_list(maelys_cli_context_t *context) {
    static const char *const names[] = {"alpha", "beta", "gamma", "delta",
        "epsilon"};
    uint64_t limit = 5u;
    (void)maelys_cli_option_unsigned(context, "limit", &limit);
    for (uint64_t i = 0u; i < limit && i < 5u; ++i) {
        char record[128];
        char line[128];
        (void)snprintf(record, sizeof(record),
            "{\"index\":%" PRIu64 ",\"name\":\"%s\"}", i, names[i]);
        (void)snprintf(line, sizeof(line), "%" PRIu64 " %s", i, names[i]);
        if (maelys_cli_emit_record(context, record, line) != 0)
            return maelys_cli_fail(context, MAELYS_CLI_CODE_IO_FAILED, NULL,
                "Could not emit record %" PRIu64 ".", i);
    }
    return maelys_cli_finish_records(context, MAELYS_CLI_EXIT_OK);
}

/* ---- check (validation report, exit 2) --------------------------------------- */

static const maelys_cli_operand_t check_operands[] = {
    {MAELYS_CLI_OPERAND("FILE",
     "File that must be private (no group or world permissions).")},
};

static int command_check(maelys_cli_context_t *context) {
    const char *path = maelys_cli_operand(context, 0u);
    const char *explanation = NULL;
    int valid = maelys_cli_check_file(path, MAELYS_CLI_FILE_REGULAR |
        MAELYS_CLI_FILE_NO_SYMLINK | MAELYS_CLI_FILE_PRIVATE, &explanation) == 0;
    if (!valid && errno == ENOENT)
        return maelys_cli_fail_errno(context, MAELYS_CLI_CODE_NOT_FOUND, errno, path);
    maelys_cli_json_writer_t data;
    maelys_cli_json_writer_init(&data);
    (void)maelys_cli_json_begin_object(&data);
    (void)maelys_cli_json_key_boolean(&data, "valid", valid);
    (void)maelys_cli_json_key_string(&data, "path", path);
    (void)maelys_cli_json_key(&data, "diagnostics");
    (void)maelys_cli_json_begin_array(&data);
    if (!valid) {
        (void)maelys_cli_json_begin_object(&data);
        (void)maelys_cli_json_key_string(&data, "code", "FILE_NOT_PRIVATE");
        (void)maelys_cli_json_key_string(&data, "message", explanation);
        (void)maelys_cli_json_end_object(&data);
    }
    (void)maelys_cli_json_end_array(&data);
    (void)maelys_cli_json_end_object(&data);
    return maelys_cli_succeed_writer(context, &data,
        valid ? "File is private." : "File is not private.",
        valid ? MAELYS_CLI_EXIT_OK : MAELYS_CLI_EXIT_VIOLATIONS);
}

/* ---- env show ----------------------------------------------------------------- */

static const maelys_cli_option_t env_options[] = {
    {MAELYS_CLI_STRING("env", "NAME[=VALUE]",
     "Overlay entry; NAME alone imports the current environment."),
     .repeatable = 1},
};

static int command_env_show(maelys_cli_context_t *context) {
    maelys_cli_environment_t environment = {0};
    size_t count = maelys_cli_option_count(context, "env");
    for (size_t i = 0u; i < count; ++i) {
        const char *assignment = maelys_cli_option_at(context, "env", i);
        if (maelys_cli_environment_append(&environment, assignment) != 0) {
            maelys_cli_environment_clear(&environment);
            return maelys_cli_fail(context, MAELYS_CLI_CODE_VALIDATION_FAILED,
                "Use NAME=VALUE or the name of a defined variable.",
                "--env %s is not a valid environment entry.", assignment);
        }
    }
    maelys_cli_json_writer_t data;
    maelys_cli_json_writer_init(&data);
    (void)maelys_cli_json_begin_object(&data);
    (void)maelys_cli_json_key_unsigned(&data, "count", (uint64_t)environment.count);
    (void)maelys_cli_json_key(&data, "entries");
    (void)maelys_cli_json_begin_array(&data);
    for (size_t i = 0u; i < environment.count; ++i) {
        (void)maelys_cli_json_begin_object(&data);
        (void)maelys_cli_json_key_string(&data, "name", environment.entries[i].name);
        (void)maelys_cli_json_key_string(&data, "value", environment.entries[i].value);
        (void)maelys_cli_json_end_object(&data);
    }
    (void)maelys_cli_json_end_array(&data);
    (void)maelys_cli_json_end_object(&data);
    maelys_cli_environment_clear(&environment);
    return maelys_cli_succeed_writer(context, &data, NULL, MAELYS_CLI_EXIT_OK);
}

/* ---- run (execute, stream) ----------------------------------------------------- */

static const maelys_cli_operand_t run_operands[] = {
    {MAELYS_CLI_OPERAND("PROGRAM", "Absolute path of the program to execute.")},
    {MAELYS_CLI_OPERAND_REST("ARG", "Arguments passed verbatim to the program.")},
};

static int command_run(maelys_cli_context_t *context) {
    size_t count = maelys_cli_operand_count(context);
    char **arguments = calloc(count + 1u, sizeof(*arguments));
    if (!arguments)
        return maelys_cli_fail_errno(context, MAELYS_CLI_CODE_UNEXPECTED, ENOMEM,
            "argument vector");
    for (size_t i = 0u; i < count; ++i)
        arguments[i] = (char *)maelys_cli_operand(context, i);
    maelys_cli_process_status_t status;
    int result = maelys_cli_process_run(arguments[0], arguments, NULL, &status);
    int saved = errno;
    free(arguments);
    if (result != 0)
        return maelys_cli_fail_errno(context, MAELYS_CLI_CODE_PROCESS_FAILED,
            saved, maelys_cli_operand(context, 0u));
    return maelys_cli_process_exit_code(&status);
}

/* ---- catalog ------------------------------------------------------------------- */

static const maelys_cli_operand_t image_operands[] = {
    {MAELYS_CLI_OPERAND_REST("ARGUMENTS",
     "Arguments passed verbatim to maelys-hello-image.")},
};

static const maelys_cli_command_t commands[] = {
    {MAELYS_CLI_READ("greet", "greet", "Greet someone.", command_greet),
     MAELYS_CLI_OPERANDS(greet_operands), MAELYS_CLI_OPTIONS(greet_options),
     MAELYS_CLI_SCHEMA(hello_greet_schema)},
    {MAELYS_CLI_READ("limits", "limits", "Echo typed option values.", command_limits),
     MAELYS_CLI_OPTIONS(limits_options), MAELYS_CLI_SCHEMA(hello_limits_schema)},
    {MAELYS_CLI_TRANSACTION("note.write", "note write", "Store a note in a file.",
     command_note_write),
     MAELYS_CLI_OPERANDS(note_operands), MAELYS_CLI_OPTIONS(note_options),
     MAELYS_CLI_SCHEMA(hello_note_write_schema)},
    {MAELYS_CLI_RECORDS("list", "list", "List sample records.", command_list),
     MAELYS_CLI_OPTIONS(list_options), MAELYS_CLI_SCHEMA(hello_list_schema)},
    {MAELYS_CLI_READ("check", "check", "Validate that a file is private.", command_check),
     MAELYS_CLI_OPERANDS(check_operands), MAELYS_CLI_SCHEMA(hello_check_schema)},
    {MAELYS_CLI_READ("env.show", "env show", "Show an environment overlay.",
     command_env_show),
     MAELYS_CLI_OPTIONS(env_options), MAELYS_CLI_SCHEMA(hello_env_show_schema)},
    {MAELYS_CLI_STREAM("run", "run", "Execute a program and relay its stdio.",
     command_run),
     MAELYS_CLI_OPERANDS(run_operands),
     .synopsis = "run PROGRAM [ARG...] | run -- PROGRAM [ARG...]"},
    {MAELYS_CLI_EXTERNAL("image", "image",
     "Delegate to the optional maelys-hello-image helper.", "maelys-hello-image"),
     MAELYS_CLI_OPERANDS(image_operands)},
};

int main(int argc, char **argv) {
    static const maelys_cli_app_t app = {
        .program = "maelys-hello",
        .product = "Maelys Hello",
        .version = HELLO_VERSION,
        .summary = "reference CLI built on libmaelys_cli",
        .commands = commands,
        .command_count = MAELYS_CLI_COUNT(commands),
    };
    return maelys_cli_main(&app, argc, argv);
}
