#!/usr/bin/env python3
"""Generate the aggregate CLI contract and Markdown reference from binaries.

Every program is asked for its own catalog through `describe`; nothing here
is a second hand-written definition.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import subprocess
import sys

DEFAULT_PROGRAMS = ("maelys", "maelys-hello")


def catalog(binary: pathlib.Path) -> dict:
    completed = subprocess.run(
        [str(binary), "describe", "--format", "json", "--compact", "--non-interactive"],
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env={"PATH": "/usr/bin:/bin", "MAELYS_COMMANDS_PATH": "/nonexistent"},
    )
    if completed.stderr:
        raise RuntimeError(f"{binary.name} polluted stderr: {completed.stderr}")
    envelope = json.loads(completed.stdout)
    if envelope.get("contract") != "agent-cli/v2" or envelope.get("ok") is not True:
        raise RuntimeError(f"{binary.name} returned an incompatible envelope")
    for command in envelope["data"]["commands"]:
        if command["usage"] != command["input"]["synopsis"]:
            raise RuntimeError(f"{binary.name}:{command['id']} has synopsis drift")
    return envelope["data"]


def markdown(programs: dict[str, dict]) -> str:
    lines = [
        "<!-- GENERATED by tools/generate_cli_reference.py; do not edit manually. -->",
        "# Maelys CLI reference",
        "",
        "Common contract: `agent-cli/v2`. For the machine-readable detail run",
        "`PROGRAM describe COMMAND_ID --format json`.",
        "",
    ]
    for name, data in programs.items():
        lines.extend((
            f"## `{name}` ({data['product']} {data['version']})",
            "",
            "| Identifier | Usage | Effect | Output | Purpose |",
            "| --- | --- | --- | --- | --- |",
        ))
        for command in data["commands"]:
            effect = command["effect"]
            if isinstance(effect, dict):
                effect = f"{effect['plan']} then {effect['apply']} with --apply"
            output = command["outputMode"]
            if command.get("protocol"):
                output += f" ({command['protocol']})"
            cells = [command["id"], f"`{command['usage']}`", effect,
                     output, command["purpose"]]
            lines.append("| " + " | ".join(str(cell).replace("|", "\\|") for cell in cells) + " |")
        lines.append("")
        lines.append("Global options:")
        lines.append("")
        for option in data["globalOptions"]:
            argument = option.get("argument")
            spelled = option["long"]
            if argument:
                choices = argument.get("choices")
                spelled += " " + ("|".join(choices) if choices else argument["name"])
            lines.append(f"- `{spelled}`: {option['summary']}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--build", required=True, type=pathlib.Path)
    parser.add_argument("--markdown", required=True, type=pathlib.Path)
    parser.add_argument("--json", required=True, type=pathlib.Path)
    parser.add_argument("programs", nargs="*", default=list(DEFAULT_PROGRAMS),
                        help="binaries to describe (default: maelys maelys-hello)")
    arguments = parser.parse_args()
    programs = {name: catalog(arguments.build / name) for name in arguments.programs}
    arguments.markdown.write_text(markdown(programs), encoding="utf-8")
    contract = {"contract": "agent-cli/v2", "programs": programs}
    arguments.json.write_text(json.dumps(contract, indent=2, sort_keys=True) + "\n",
                              encoding="utf-8")
    print(f"generated {arguments.markdown} and {arguments.json}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
