#!/usr/bin/env python3
"""Generate the aggregate CLI contract and Markdown reference from binaries.

Every program is asked for its own catalog through `describe`; nothing here
is a second hand-written definition.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import subprocess
import sys

DEFAULT_PROGRAMS = ("maelys", "maelys-hello")


VERSION_MEMBERS = ("version", "framework")


def neutralize(data: dict, identifiers: set[str] | None) -> None:
    """Describe the commands as available whatever the host.

    A catalog command declared `.unavailable` on some hosts (a Linux-only
    command built on macOS) makes the described contract host-dependent,
    and a committed contract must describe the complete product. With
    `identifiers` None every command is neutralized; otherwise only those.
    """
    for command in data["commands"]:
        if identifiers is None or command["id"] in identifiers:
            command["available"] = True
            command.pop("unavailableReason", None)


def catalog(binary: pathlib.Path, include_versions: bool) -> dict:
    completed = subprocess.run(
        [str(binary), "describe", "--format", "json", "--compact", "--non-interactive"],
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env={"PATH": "/usr/bin:/bin", "MAELYS_COMMANDS_PATH": "/nonexistent"},
    )
    if completed.stderr:
        raise RuntimeError(f"{binary.name} polluted stderr: {completed.stderr}")
    envelope = json.loads(completed.stdout)
    if envelope.get("contract") != "agent-cli/v2" or envelope.get("ok") is not True:
        raise RuntimeError(f"{binary.name} returned an incompatible envelope")
    for command in envelope["data"]["commands"]:
        if command["usage"] != command["input"]["synopsis"]:
            raise RuntimeError(f"{binary.name}:{command['id']} has synopsis drift")
    data = envelope["data"]
    if not include_versions:
        # Release-neutral by default: the committed contract must not change
        # on every version bump, so contract-check can run in `make check`.
        for member in VERSION_MEMBERS:
            data.pop(member, None)
    return data


DEFAULT_TITLE = "Maelys CLI reference"
DEFAULT_INTRO = (
    "Common contract: `agent-cli/v2`. For the machine-readable detail run\n"
    "`PROGRAM describe COMMAND_ID --format json`."
)
DEFAULT_COLUMNS = ("Identifier", "Usage", "Effect", "Output", "Purpose")


def markdown(programs: dict[str, dict], title: str, intro: str,
             columns: tuple[str, ...], global_label: str) -> str:
    lines = [
        "<!-- GENERATED by maelys-cli-reference; do not edit manually. -->",
        f"# {title}",
        "",
        intro,
        "",
    ]
    for name, data in programs.items():
        heading = f"## `{name}` ({data['product']}"
        heading += f" {data['version']})" if "version" in data else ")"
        lines.extend((
            heading,
            "",
            "| " + " | ".join(columns) + " |",
            "| " + " | ".join("---" for _ in columns) + " |",
        ))
        for command in data["commands"]:
            effect = command["effect"]
            if isinstance(effect, dict):
                effect = f"{effect['plan']} then {effect['apply']} with --apply"
            output = command["outputMode"]
            if command.get("protocol"):
                output += f" ({command['protocol']})"
            cells = [command["id"], f"`{command['usage']}`", effect,
                     output, command["purpose"]]
            lines.append("| " + " | ".join(str(cell).replace("|", "\\|") for cell in cells) + " |")
        lines.append("")
        lines.append(global_label)
        lines.append("")
        for option in data["globalOptions"]:
            argument = option.get("argument")
            spelled = option["long"]
            if argument:
                choices = argument.get("choices")
                spelled += " " + ("|".join(choices) if choices else argument["name"])
            lines.append(f"- `{spelled}`: {option['summary']}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--build", required=True, type=pathlib.Path)
    parser.add_argument("--markdown", required=True, type=pathlib.Path)
    parser.add_argument("--json", required=True, type=pathlib.Path)
    parser.add_argument("--include-versions", action="store_true",
                        help="keep product and framework versions in the output")
    parser.add_argument("--neutral-availability", nargs="?", const="*", metavar="IDS",
                        help="describe commands as available whatever the host "
                             "(all of them, or the comma-separated identifiers)")
    parser.add_argument("--title", default=DEFAULT_TITLE,
                        help="page title (products keep their own language)")
    parser.add_argument("--intro", default=DEFAULT_INTRO,
                        help="paragraph under the title; literal Markdown")
    parser.add_argument("--intro-file", type=pathlib.Path,
                        help="file whose content replaces --intro")
    parser.add_argument("--columns", default="|".join(DEFAULT_COLUMNS),
                        help="five table headers separated by '|'")
    parser.add_argument("--global-label", default="Global options:",
                        help="label of the global options list")
    parser.add_argument("programs", nargs="*", default=list(DEFAULT_PROGRAMS),
                        help="binaries to describe (default: maelys maelys-hello)")
    arguments = parser.parse_args()
    programs = {name: catalog(arguments.build / name, arguments.include_versions)
                for name in arguments.programs}
    if arguments.neutral_availability is not None:
        identifiers = None
        if arguments.neutral_availability != "*":
            identifiers = set(arguments.neutral_availability.split(","))
        for data in programs.values():
            neutralize(data, identifiers)
    columns = tuple(arguments.columns.split("|"))
    if len(columns) != 5:
        parser.error("--columns needs exactly five headers")
    intro = arguments.intro
    if arguments.intro_file is not None:
        intro = arguments.intro_file.read_text(encoding="utf-8").rstrip()
    arguments.markdown.write_text(
        markdown(programs, arguments.title, intro, columns, arguments.global_label),
        encoding="utf-8")
    contract = {"contract": "agent-cli/v2", "programs": programs}
    arguments.json.write_text(json.dumps(contract, indent=2, sort_keys=True) + "\n",
                              encoding="utf-8")
    print(f"generated {arguments.markdown} and {arguments.json}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
